[build]
  command = "make build"
  functions = "functions"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/MobeenAshraf/serverless-go"
[[redirects]]
  from = "/"
  to = "/.netlify/functions/serverless-go"
  status = 200
  force = true
